# Generated by Django 3.0.8 on 2021-02-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confcurso', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restricoes',
            name='dias_semana',
        ),
        migrations.AddField(
            model_name='restricoes',
            name='hora_fim',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restricoes',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
