# Generated by Django 3.0.8 on 2021-02-17 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confcurso', '0002_auto_20210202_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='restricoes',
            name='semestre_atual',
            field=models.CharField(blank=True, choices=[('1', '1 Semestre'), ('2', '2 Semestre')], max_length=1, null=True),
        ),
    ]
