# Generated by Django 3.0.8 on 2020-08-13 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('bloco', models.CharField(blank=True, max_length=2)),
                ('capacidade', models.CharField(max_length=4)),
                ('tipo_lab', models.CharField(choices=[('S', 'Laboratório sem computadores'), ('C', 'Laboratório com computadores')], max_length=1)),
                ('status', models.CharField(choices=[('1', 'Ativo'), ('2', 'Inativo')], max_length=1)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
