# Generated by Django 3.0.8 on 2020-08-13 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='tipo_lab',
            field=models.CharField(choices=[('1', 'Laboratório sem computadores'), ('2', 'Laboratório com computadores')], max_length=1),
        ),
    ]
