# Generated by Django 3.0.8 on 2020-08-13 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0002_auto_20200812_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='tipo_lab',
            field=models.CharField(choices=[('0', 'Laboratório sem computadores'), ('1', 'Laboratório com computadores')], max_length=1),
        ),
    ]
