# Generated by Django 3.0.8 on 2020-08-23 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, null=True)),
                ('matricula', models.CharField(max_length=30, unique=True)),
                ('email', models.CharField(max_length=100)),
                ('jornada_sem', models.IntegerField()),
                ('max_aulas_dia', models.IntegerField()),
                ('status', models.CharField(choices=[('1', 'Ativo'), ('2', 'Inativo')], max_length=1)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
