# Generated by Django 3.0.8 on 2021-02-04 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='status',
            field=models.CharField(choices=[('1', 'Ativo'), ('2', 'Inativo')], default=1, max_length=1),
        ),
    ]
