# Generated by Django 3.0.8 on 2020-09-27 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0002_turma_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='qtd_alunos',
            field=models.IntegerField(default=20, max_length=4),
            preserve_default=False,
        ),
    ]
