# Generated by Django 3.0.8 on 2021-02-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0003_turma_qtd_alunos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='qtd_alunos',
            field=models.IntegerField(),
        ),
    ]
