# Generated by Django 3.0.8 on 2021-02-17 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0004_auto_20210202_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'Ativo'), ('2', 'Inativo')], default=1, max_length=1),
        ),
    ]
