# Generated by Django 3.0.8 on 2021-02-02 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disciplinas', '0002_auto_20200823_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaDisciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('1', 'Teórica'), ('2', 'Prática')], max_length=1)),
                ('n_alunos', models.IntegerField()),
                ('disciplinas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disciplinas.Disciplina')),
            ],
        ),
    ]
