# Generated by Django 3.0.8 on 2021-02-02 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disciplinas', '0003_categoriadisciplina'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoriadisciplina',
            old_name='nome',
            new_name='categoria',
        ),
    ]
