# Generated by Django 3.0.8 on 2021-02-03 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disciplinas', '0004_auto_20210202_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoriadisciplina',
            name='disciplinas',
        ),
        migrations.AddField(
            model_name='disciplina',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='disciplinas.CategoriaDisciplina'),
        ),
        migrations.AlterField(
            model_name='categoriadisciplina',
            name='n_alunos',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
