# Generated by Django 3.0.8 on 2021-02-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplinas', '0005_auto_20210203_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='categoria',
            field=models.CharField(choices=[('1', 'Teórica'), ('2', 'Prática')], max_length=1),
        ),
        migrations.DeleteModel(
            name='CategoriaDisciplina',
        ),
    ]
